name: Bot de Trading Avanzado

on:
  schedule:
    # Se ejecuta cada 5 minutos. Puedes cambiarlo si quieres.
    # Ejemplo: cada 1 hora -> - cron: '0 * * * *'
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde GitHub

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios crypto

      - name: Run Bot
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_SECRET_KEY: ${{ secrets.BINANCE_SECRET_KEY }}
          BINANCE_ENDPOINT: ${{ secrets.BINANCE_ENDPOINT }}
        run: node bot.js
